services:
  backend:
    build:
      context: /backend/server
      dockerfile: Dockerfile
    image: node:18
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d