services:

  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - node_modules:/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080
  
  backend:
    build:
      context: ./backend/server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://test:test@db:5432/test
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d

volumes:
    db_data:
    node_modules: